<?php

$twitterAuth = array(
    "oauth_access_token" => "2369782550-T84y5BgNnCGp0ayHwoYDctokfKKuhTpCSQZoWTx",
    "oauth_access_token_secret" =>"7IPL8dXhkQ1ibGluaShBAJDu6g3upkTtv07BzqZUMJtcC",
    "consumer_key" => "HmiYNi8vFkHrOoN8oRRuJQ",
    "consumer_secret" => "31bzh8wKObVUfPc8DhQURE01BVW1Bty5rc21wC0eA"
);

$twitterApiUrls = array(
        "send_dm" => "https://api.twitter.com/1.1/direct_messages/new.json",
        "post_tweet" => "https://api.twitter.com/1.1/statuses/update.json",
        "get_followers_list" => "https://api.twitter.com/1.1/followers/list.json",
        "get_followers_id" => "https://api.twitter.com/1.1/followers/ids.json"
    );

?>